#include "stdafx.h"


PGDLLEXPORT Datum encfloatin(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloatout(PG_FUNCTION_ARGS);

PGDLLEXPORT Datum encfloat_enc(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_dec(PG_FUNCTION_ARGS);

PGDLLEXPORT Datum encfloat_eq(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_ne(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_lt(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_le(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_gt(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_ge(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_cmp(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_add(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_subs(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_mult(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_mod(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_div(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_exp(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_addfinal(PG_FUNCTION_ARGS);
PGDLLEXPORT Datum encfloat_avgfinal(PG_FUNCTION_ARGS);
